import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(scriptDir, "..");
const repoRoot = path.resolve(packageRoot, "..", "..");
const inputPath = path.join(repoRoot, "apps", "hub_api", "openapi.json");
const outputPath = path.join(packageRoot, "src", "generated", "api-types.ts");

const header = `// -----------------------------------------------------------------------------\n// <auto-generated>\n// Generated from apps/hub_api/openapi.json by packages/sdk/scripts/generate-openapi-types.ts.\n// Do not edit this file directly; update FastAPI/Pydantic models and regenerate.\n// -----------------------------------------------------------------------------\n\n`;

async function main() {
  const rawSchema = await readFile(inputPath, "utf8");
  const schema = JSON.parse(rawSchema) as Record<string, unknown>;
  const ast = await openapiTS(schema, {
    alphabetize: true,
    defaultNonNullable: false,
    rootTypes: true,
    rootTypesNoSchemaPrefix: true,
  });
  const contents = `${header}${astToString(ast)}`;

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, contents, "utf8");

  console.log(`Generated ${path.relative(repoRoot, outputPath)} from ${path.relative(repoRoot, inputPath)}`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
